Traceback (most recent call last):
  File "/Users/jordannewberry/Prime/Week-10-Lecture-Stuff/python-practice/lesson35-2.py", line 4, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
